# Generated by Django 3.1.2 on 2020-10-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('OPEN_DUP', 'Open - Dup'), ('CLOSED', 'Closed'), ('CLOSED_DUP', 'Closed - Dup')], max_length=15)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('service_request_number', models.CharField(max_length=20)),
                ('type_of_service_request', models.CharField(choices=[('ABANDONED_VEHICLE', 'Abandoned Vehicle Complaint'), ('ALLEY_LIGHT_OUT', 'Alley Light Out'), ('GARBAGE_CART', 'Garbage Cart Black Maintenance/Replacement'), ('GRAFFITI', 'Graffiti Removal'), ('POT_HOLE', 'Pothole in Street'), ('RODENT_BAITING', 'Rodent Baiting/Rat Complaint'), ('SANITATION_CODE', 'Sanitation Code Violation'), ('STREET_LIGHTS_ALL_OUT', 'Street Lights - All/Out'), ('STREET_LIGHT_ONE_OUT', 'Street Light Out'), ('TREE_DEBRIS', 'Tree Debris'), ('TREE_TRIM', 'Tree Trim')], max_length=30)),
                ('current_activity', models.CharField(blank=True, max_length=30, null=True)),
                ('most_recent_action', models.CharField(blank=True, max_length=30, null=True)),
                ('street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('zip_codes', models.IntegerField(blank=True, null=True)),
                ('x_coordinate', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('y_coordinate', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('ward', models.IntegerField(blank=True, null=True)),
                ('wards', models.IntegerField(blank=True, null=True)),
                ('historical_wards_03_15', models.IntegerField(blank=True, null=True)),
                ('police_district', models.IntegerField(blank=True, null=True)),
                ('community_area', models.IntegerField(blank=True, null=True)),
                ('community_areas', models.IntegerField(blank=True, null=True)),
                ('ssa', models.IntegerField(blank=True, null=True)),
                ('census_tracts', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
    ]
