# Generated by Django 3.1.3 on 2020-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('OPEN_DUP', 'Open - Dup'), ('COMPLETED', 'Closed'), ('COMPLETED_DUP', 'Closed - Dup')], max_length=15),
        ),
    ]
