# Generated by Django 3.1.3 on 2020-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abandonedvehicle',
            name='days_of_report_as_parked',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
