# Generated by Django 3.1.3 on 2020-11-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['type_of_service_request'], name='incidents_type_of_7f9a61_idx'),
        ),
    ]
