# Generated by Django 3.1.3 on 2020-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='numberofcartsandpotholes',
            index=models.Index(fields=['number_of_elements'], name='number_of_c_number__2bd9fc_idx'),
        ),
    ]
