# Generated by Django 3.1.3 on 2020-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='abandonedvehicle',
            index=models.Index(fields=['license_plate'], name='abandoned_v_license_80a8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedvehicle',
            index=models.Index(fields=['vehicle_color'], name='abandoned_v_vehicle_d0fcb3_idx'),
        ),
    ]
