# Generated by Django 3.1.3 on 2020-11-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0002_auto_20201107_2001'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['creation_date', 'status', 'completion_date', 'service_request_number', 'type_of_service_request', 'current_activity', 'most_recent_action', 'street_address', 'zip_code'], name='incidents_creatio_847d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate', 'vehicle_make_model', 'vehicle_color'], name='vehicles_license_d6efdf_idx'),
        ),
    ]
