# Generated by Django 3.1.3 on 2020-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0002_auto_20201104_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('OPEN_DUP', 'Open - Dup'), ('COMPLETED', 'Completed'), ('COMPLETED_DUP', 'Completed - Dup')], max_length=15),
        ),
    ]
