# Generated by Django 3.1.3 on 2020-11-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0002_auto_20201122_1954'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['creation_date'], name='incidents_creatio_c7a7cb_idx'),
        ),
    ]
