# Generated by Django 3.1.3 on 2020-11-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0003_auto_20201122_2129'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['zip_code'], name='incidents_zip_cod_d511fb_idx'),
        ),
    ]
