# Generated by Django 3.1.3 on 2020-11-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago_incidents', '0003_auto_20201108_0005'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incident',
            name='incidents_creatio_847d8b_idx',
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['creation_date', 'status', 'completion_date', 'service_request_number', 'type_of_service_request', 'street_address'], name='incidents_creatio_549343_idx'),
        ),
    ]
